import {SpaceAPI,telegram,uuid} from './api.js?v=20261003-checkpoints';
import {GAME_DATA} from './game-data.js?v=20261003-checkpoints';
import {Sound} from './audio.js';
import {SpaceScene} from './scene.js';

const api=new SpaceAPI(),sound=new Sound(),scene=new SpaceScene(document.querySelector('#space'));
const screen=document.querySelector('#screen'),hud=document.querySelector('#hud');
const storage='orbital:'+(telegram?.initDataUnsafe?.user?.id||api.browserId);
let roster=[],astronaut=0,otherName='',state=null,pending=null,selected=null;
let running=false,remaining=0,deadline=0,tick,paused=false,busy=false,afterFeedback=null;
let flightOffset=0,flightDistance=180;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,cls='primary')=>`<button class="${cls}" type="button" data-action="${action}">${label}</button>`;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const shuffle=items=>{const out=items.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;};
function persist(){try{localStorage.setItem(storage,JSON.stringify({state,pending,selected,remaining,astronaut,otherName}));}catch{}}
function saved(){try{return JSON.parse(localStorage.getItem(storage)||'null');}catch{return null;}}
function status(text){document.querySelector('#connection').textContent=text;}
function haptic(type){try{telegram?.HapticFeedback?.notificationOccurred(type);}catch{}}
function view(stage,html){document.body.dataset.stage=String(stage);screen.innerHTML=html;screen.classList.add('entering');hud.hidden=stage==='welcome';document.querySelector('#pause').hidden=!['1','2'].includes(String(stage));}
function setupTelegram(){if(!api.authenticated)return;telegram.expand();telegram.setHeaderColor?.('#070b11');telegram.setBackgroundColor?.('#070b11');telegram.enableClosingConfirmation?.();telegram.BackButton?.onClick(()=>pause());}
function questionOrder(){return [1,2].flatMap(stage=>shuffle(GAME_DATA.questions.filter(question=>question.stage===stage)).map(question=>({...question,options:shuffle(question.options)})));}
function localMission(request,remote){return {attempt:request.attempt,name:remote.name||request.name,student:request.student,status:'active',index:0,lives:3,order:questionOrder(),answers:[],checkpoint:'entered',delivery:'none',practice:false,question:null};}
function current(){return state.order[state.index]||null;}
function welcome(message=''){
  stopTimer();scene.set(0);state=null;selected=null;pending=null;
  const all=[...roster,{id:'other',name:otherName||'Other',color:'white'}],pupil=all[astronaut]||all[0],image='./assets/astronaut-'+pupil.color+'.webp';
  view('welcome',`<section class="welcome"><p class="eyebrow">Learn Core / Gateway B1 / Unit 1</p><h1 class="title">Beyond<span>Earth.</span></h1><p class="hint">43 words. Two stages. One mission.</p><div class="carousel">${button('‹','previous','arrow')}<img class="astronaut" src="${image}" onerror="this.onerror=null;this.src='./assets/astronaut.jpg'" alt="Astronaut in a ${esc(pupil.color)} suit">${button('›','next','arrow')}</div><h2 class="name">${esc(pupil.displayName||pupil.name)}</h2><p class="hint">Choose your astronaut</p><div class="actions">${button('Launch mission →','launch')}${button(sound.enabled?'Sound on · ♫':'Sound off · ♫','sound','secondary')}</div><p class="hint">${esc(message||'Complete both stages → grade 5. Mission failed → grade 2.')}</p></section>`);
  document.querySelector('#sound').textContent=sound.enabled?'♫ On':'♫ Off';
}
function modal(title,content,actions){document.querySelector('.modal')?.remove();const el=document.createElement('div');el.className='modal';el.innerHTML=`<section class="dialog" role="dialog" aria-modal="true" aria-label="${esc(title)}"><h2>${esc(title)}</h2>${content}<div class="actions">${actions}</div></section>`;document.body.append(el);screen.inert=true;el.querySelector('button')?.focus();}
function closeModal(){document.querySelector('.modal')?.remove();screen.inert=false;}
function askName(){modal('Your astronaut',`<label for="nameInput">Your name</label><input class="field" id="nameInput" autocomplete="name" maxlength="60" placeholder="First and last name" value="${esc(otherName)}">`,button('Continue →','name-save')+button('Back','modal-close','secondary'));document.querySelector('#nameInput').focus();}
async function launch(){await sound.unlock().catch(()=>{});if(astronaut===roster.length&&!otherName){askName();return;}await start();}
async function start(){closeModal();const pupil=roster[astronaut]||{id:'other',name:otherName};pending={action:'start',attempt:uuid(),student:pupil.id,name:pupil.name,requestId:uuid()};state=null;persist();await runPending();}
async function runPending(){
  if(busy||!pending)return;busy=true;stopTimer();const request=pending;
  if(request.action==='start')view(1,`<section class="result"><p class="eyebrow">Mission control</p><h1 class="title">Preparing<br>flight.</h1><p class="checking">Creating your first checkpoint…</p></section>`);else status(request.checkpoint==='stage1'?'Saving Stage 1 checkpoint…':'Saving mission result…');
  try{const remote=await api.call(request.action,request);pending=null;if(request.action==='start')state=localMission(request,remote);else Object.assign(state,{status:remote.status,index:remote.index,lives:remote.lives,checkpoint:remote.checkpoint,grade:remote.grade,bestGrade:remote.bestGrade,delivery:remote.delivery});persist();if(request.action==='start')showQuestion();return remote;}catch(error){connectionError(error);throw error;}finally{busy=false;}
}
function connectionError(error){persist();modal('Signal lost',`<p>${esc(error.message)}</p><p>Your local flight log is kept. Retry when the connection returns.</p>`,button('Retry connection','retry')+button('Exit mission','quit','secondary'));}
function updateHud(){const q=current();document.querySelector('#stage').textContent=state?.status==='active'?'Stage '+(q?.stage||2):'Mission result';document.querySelector('#progress').textContent=state?.status==='active'?`${state.index%43+1} / 43`:state?`${state.index} / 86`:'';const lives=state?.lives??3,hearts=document.querySelector('#hearts');hearts.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);hearts.setAttribute('aria-label',`${lives} lives remaining`);document.querySelector('#sound').textContent=sound.enabled?'♫ On':'♫ Off';}
function showQuestion(restoredTime){closeModal();paused=false;selected=null;const q=current();if(!q)return;scene.set(q.stage);scene.choose(1);updateHud();view(q.stage,`<section class="mission ${q.stage===1?'stage-one':'stage-two'}"><p class="eyebrow">${q.stage===1?'Word navigation':'Context navigation'}</p><h1 class="prompt">${esc(q.prompt_en).replace(/_{2,}/g,'<span class="blank">______</span>')}</h1><div class="timer" role="timer"><span id="seconds"></span><progress id="timebar" max="${q.stage===1?GAME_DATA.timing.stage1:GAME_DATA.timing.stage2}" value="${q.stage===1?GAME_DATA.timing.stage1:GAME_DATA.timing.stage2}"></progress></div><div class="lanes">${q.options.map((option,index)=>`<button type="button" class="lane" data-lane="${index}" aria-pressed="false">${esc(option.text)}</button>`).join('')}</div><p class="hint">${q.stage===1?'← Swipe left · ↑ Centre · Swipe right →<br>Or tap a word · answer locks at zero':'Choose the word that fits the whole sentence.'}</p></section>`);
  if(q.stage===1){const lanes=document.querySelector('.lanes'),end=scene.approachY()-lanes.offsetHeight;flightOffset=end-lanes.getBoundingClientRect().top;flightDistance=Math.max(15,Math.min(180,end-document.querySelector('.timer').getBoundingClientRect().bottom-16));}
  telegram?.BackButton?.show();remaining=restoredTime??(q.stage===1?GAME_DATA.timing.stage1:GAME_DATA.timing.stage2)*1000;startTimer();if(document.hidden)pause();
}
function startTimer(){deadline=performance.now()+remaining;running=true;tick=setInterval(()=>{remaining=Math.max(0,deadline-performance.now());drawTimer();if(remaining===0){const q=current();submit(selected===null?null:q.options[selected].id);}},50);drawTimer();}
function drawTimer(){const seconds=document.querySelector('#seconds'),bar=document.querySelector('#timebar');if(seconds)seconds.textContent=(remaining/1000).toFixed(1)+' s';if(bar)bar.value=remaining/1000;document.querySelector('.timer')?.classList.toggle('urgent',remaining<1500);const q=current();if(q?.stage===1){const lanes=document.querySelector('.lanes');if(lanes)lanes.style.transform=`translateY(${flightOffset-flightDistance*remaining/(GAME_DATA.timing.stage1*1000)}px)`;}}
function stopTimer(){clearInterval(tick);running=false;}
function select(index){if(!running||busy||paused||!current())return;selected=index;scene.choose(index);sound.effect('select');document.querySelectorAll('.lane').forEach((el,i)=>{el.classList.toggle('selected',i===index);el.setAttribute('aria-pressed',String(i===index));});persist();if(current().stage===2)submit(current().options[index].id);}
async function checkpoint(checkpoint,answers){pending={action:'checkpoint',attempt:state.attempt,checkpoint,answers,requestId:uuid()};persist();return runPending();}
async function submit(option){
  if(!running||busy)return;stopTimer();const q=current(),correct=option===q.correct_option_id;state.answers.push({question:q.id,option,correct});state.index++;if(!correct)state.lives--;persist();
  if(correct){scene.confirm();sound.effect('correct');haptic('success');}else{scene.impact();sound.effect('wrong');haptic('error');}
  await feedback({correct,answer:q.options.find(item=>item.id===q.correct_option_id).text,explanation:q.feedback_en},q.stage);
}
async function feedback(feedback,stage){
  if(!feedback.correct&&state.lives<1){scene.explode();sound.effect('explode');await delay(1050);await checkpoint('final',state.checkpoint==='stage1-complete'?state.answers.slice(43):state.answers);await result();return;}
  view(stage,`<section class="result flight-feedback ${feedback.correct?'confirmed':'impact'}"><p class="eyebrow">${feedback.correct?'Trajectory confirmed':'Meteor strike'}</p><h1 class="title">${esc(feedback.answer)}</h1><p class="feedback ${feedback.correct?'correct':'wrong'}">${esc(feedback.explanation)}</p>${!feedback.correct?button('Continue →','continue'):''}</section>`);
  afterFeedback=async()=>{if(stage===1&&state.index===43){await checkpoint('stage1',state.answers.slice(0,43));await stageTwo();}else if(state.index===86){await checkpoint('final',state.answers.slice(43));await result();}else showQuestion();};
  if(feedback.correct){await delay(850);const next=afterFeedback;afterFeedback=null;await next();}
}
async function stageTwo(){scene.boost();sound.effect('boost');view(2,`<section class="result stage-intro"><p class="eyebrow">Stage 1 checkpoint saved</p><h1 class="title">Stage 2</h1><p>Put the words into context.</p></section>`);await delay(2100);showQuestion();}
async function result(){stopTimer();paused=false;telegram?.BackButton?.hide();telegram?.disableClosingConfirmation?.();const win=state.status==='completed';if(win)sound.effect('win');view('result',`<section class="result"><p class="eyebrow">${win?'Destination reached':'Mission lost'}</p><h1 class="title">${win?'Mission<br>complete.':'Start<br>again.'}</h1><p>${esc(state.name)}</p><p class="score">${state.grade}</p><p>${win?'Completed':'Not completed'} · ${state.index} / 86 answers</p><p class="hint" id="receipt">${receipt()}</p><div class="actions">${button('Start again →','restart')}${button('Choose astronaut','home','secondary')}${state.delivery==='pending'?button('Retry sending result','delivery','secondary'):''}</div></section>`);persist();}
function receipt(){if(state.delivery==='sent')return `Grade saved. Report sent to your teacher through the bot.${state.bestGrade===5?' Final assignment grade: 5.':''}`;return 'Grade saved. Bot delivery is pending. Tap Retry sending result.';}
function pause(){if(!running||!state||state.status!=='active'||paused)return;stopTimer();paused=true;persist();sound.suspend();modal('Flight paused','<p>Your timer is stopped. Resume when you are ready.</p>',button('Resume flight','resume')+button('End attempt','quit','secondary'));}
async function resume(){closeModal();paused=false;await sound.unlock().catch(()=>{});if(remaining>0)startTimer();else showQuestion();}
async function quit(){closeModal();stopTimer();if(!state){welcome();return;}if(!state.answers.length){pending={action:'abort',attempt:state.attempt};await runPending();await result();return;}await checkpoint('final',state.checkpoint==='stage1-complete'?state.answers.slice(43):state.answers);await result();}
async function bootstrap(){setupTelegram();welcome('Preparing mission control…');try{const config=await api.call('config');roster=config.roster;if(!roster.length)throw new Error('Astronaut roster is unavailable. Please try again.');const old=saved();astronaut=Math.min(old?.astronaut||0,roster.length);otherName=old?.otherName||'';if(old?.state?.delivery==='pending'){state=old.state;pending={action:'resume',attempt:state.attempt};await runPending();await result();return;}if(old?.state?.status==='active'){state=old.state;remaining=old.remaining>0?old.remaining:(current().stage===1?GAME_DATA.timing.stage1:GAME_DATA.timing.stage2)*1000;modal('Resume mission','<p>Your local flight log is ready.</p>',button('Resume flight','restore')+button('End attempt','quit','secondary'));return;}welcome();}catch(error){welcome(error.message);modal('Connection unavailable',`<p>${esc(error.message)}</p>`,button('Retry','reload'));}}
async function action(name){if(name==='previous'||name==='next'){astronaut=(astronaut+(name==='next'?1:roster.length))%(roster.length+1);welcome();}if(name==='launch')await launch();if(name==='name-save'){const value=document.querySelector('#nameInput').value.trim();if(value.length<2||value.length>60||/[<>\x00-\x1f]/.test(value)){document.querySelector('#nameInput').setCustomValidity('Enter your name using letters, spaces and normal punctuation.');document.querySelector('#nameInput').reportValidity();return;}otherName=value;closeModal();await start();}if(name==='modal-close')closeModal();if(name==='retry')await runPending();if(name==='pause')pause();if(name==='resume')await resume();if(name==='quit')await quit();if(name==='restore'){closeModal();await sound.unlock().catch(()=>{});showQuestion(remaining);}if(name==='continue'&&afterFeedback){const next=afterFeedback;afterFeedback=null;await next();}if(name==='restart'){telegram?.enableClosingConfirmation?.();await start();}if(name==='home'){welcome();persist();}if(name==='sound'){await sound.unlock().catch(()=>{});sound.set(!sound.enabled);updateHud();if(!state)welcome();}if(name==='delivery'){pending={action:'resume',attempt:state.attempt};await runPending();await result();}if(name==='reload')location.reload();}
document.addEventListener('click',event=>{const lane=event.target.closest('[data-lane]');if(lane)select(Number(lane.dataset.lane));const target=event.target.closest('[data-action]');if(target)action(target.dataset.action).catch(connectionError);});
document.addEventListener('keydown',event=>{if(event.key==='Enter'&&document.querySelector('#nameInput')){action('name-save').catch(connectionError);return;}const lane={ArrowLeft:0,ArrowUp:1,ArrowRight:2,'1':0,'2':1,'3':2}[event.key];if(lane!==undefined&&running){event.preventDefault();select(lane);}});
let pointer;screen.addEventListener('pointerdown',event=>{if(running)pointer={x:event.clientX,y:event.clientY};});screen.addEventListener('pointerup',event=>{if(!pointer||!running||current()?.stage!==1){pointer=null;return;}const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;pointer=null;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;select(Math.abs(dx)>Math.abs(dy)?(dx<0?0:2):1);});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(running)pause();sound.suspend();}});window.addEventListener('pagehide',persist);setInterval(()=>{if(running)persist();},1000);bootstrap();
